Updated dependency version in the sample app
aws-observability/aws-otel-go pull request #150
Opened 2022-03-03 22:00 UTC by ruthvik17

Updated the versions for the go dependencies in the sample app.

2022-03-03 22:26 UTC, bryan-aguilar requested changes
Can you please upgrade the version of GO that is being used to 1.17

2022-03-03 22:28 UTC, bryan-aguilar commented
Did you test to make sure the sample app functions properly with these dependency updates?

2022-03-23 18:43 UTC, bryan-aguilar commented on sampleapp/main.go
> +	fmt.Println("endpoint ", endpoint)
```suggestion
```

2022-03-23 18:43 UTC, bryan-aguilar commented on sampleapp/main.go
> +	fmt.Println("ctx ", ctx)
```suggestion
```

2022-03-23 18:44 UTC, bryan-aguilar commented on sampleapp/main.go
> +	fmt.Println("service ", service)
```suggestion
```

2022-03-23 18:45 UTC, bryan-aguilar commented on sampleapp/README.md
>  1. Install Go 1.15 or higher
```suggestion
1. Install Go 1.16 or higher
```

2022-03-23 19:45 UTC, bryan-aguilar approved these changes

2022-03-23 23:08 UTC, Aneurysm9 commented on sampleapp/main.go
> +		endpoint = "https://localhost:4317" // setting default endpoint for exporter
Why is this change made?

2022-03-23 23:18 UTC, ruthvik17 commented on sampleapp/main.go
> +		endpoint = "https://localhost:4317" // setting default endpoint for exporter
The default variables for the endpoint is mentioned as https://localhost:4317 as per [here]( https://github.com/open-telemetry/opentelemetry-go/tree/exporters/otlp/otlptrace/otlptracegrpc/v1.5.0/exporters/otlp/otlptrace#environment-variables).

I thought it might make a difference.

2022-04-06 19:41 UTC, Aneurysm9 commented on sampleapp/main.go
> +		endpoint = "https://localhost:4317" // setting default endpoint for exporter
can we drop it from this PR and deal with it separately?  Since this is using gRPC I'm not sure the change matters except that it might trigger an attempt to validate TLS certs that are not likely to be there.

2022-04-06 22:07 UTC, Aneurysm9 commented
After https://github.com/aws-observability/aws-otel-go/pull/167 the only change left we need to make is to the readme.  Please open a new PR for that.

2022-04-06 22:07 UTC, closed without merging